### ISSUE TITLE
辭庫來源

### ISSUE THREAD

**Issue by bingluen** [itszero/HasGoogleFixedItYet#3]
建議參考國家教育研究院的兩岸對照名詞相關表格，納入檢測詞彙

https://terms.naer.edu.tw/download/

**Comment by itszero** [comment]
感謝推薦，不過那個詞量實在太大了。我並不是要爬 Google Translate 做成辭典所以不允考慮 🙏

如果您有什麼日常生活中常見被 Google 翻譯錯的詞彙，我很樂意斟酌加入！
