### ISSUE TITLE
Proposal for simplifying the architecture

### ISSUE THREAD

**Issue by kevin940726** [itszero/HasGoogleFixedItYet#7]
不知道是不是因為有什麼特別的需求或是為了讓未來有更多其他的發展方向，我發現這個網站的架構似乎稍微複雜了一些。

目前的架構就我觀察大概是：
- Ruby 後端
- postgresql/sqlite3 資料庫
- Svelte 前端 (CSR)

根據此專案的性質，翻譯檔的更新頻率和大小都不會太大，也許我們可以只用靜態的 `json` 檔來儲存這些資料就好，直接存放在 repository 中，並直接透過 git 版控。在這樣的架構下，其實整個前端可以只是一個靜態頁面，可以透過 svelte prerender 後放在 CDN 上增加瀏覽的速度，由於資料來源只是靜態的 `json` 檔，故也不需要額外的 API call，節省伺服器的開銷和流量，可以直接用 GitHub pages 或是免費的 Netlify 來部署。

至於定期更新資料的方式可以透過 GitHub actions 來解決，可以設定 cronjob 讓它每天定期拉最新的資料，重新 build 一次前端後發佈到 Netlify 上。

更新後的架構大概如下：
- Svelte 前端 (SSR)
- Netlify 部署
- GitHub actions 定期更新資料和部署前端

好處：
- 降低管理成本，整個專案可以縮減到只剩下 svelte 的前端程式碼和自定義的 GitHub actions。
- 貢獻容易，貢獻者可以只修改 `json` 檔。
- 因為網站只是純前端，串接 Netlify 等的 preview 的服務會變得相當容易，意即每個 PR 都可以有獨立的 PR preview 網址，降低管理者的管理成本。

好奇想知道你的想法 :)，不知道是不是還有什麼我沒想到的其他考量？

或許只是因為這樣的架構是最簡單方便的？我同意如果沒有什麼特別好的優點的話的確不需要去更改架構，若是如此歡迎關閉這個 issue 😄。

**Comment by itszero** [comment]
哈哈，確實這樣會比較簡單。我當初會做這樣主要只是不喜歡 commit history 被搞的亂七八糟（當然也是可以想辦法繞過這個問題，用不同 branch 等等之類的），然後想說存成一個 DB，以後想要 query 什麼比較方便一點。管理跟營運成本對我來說目前不是太大的問題。瀏覽速度本身我有稍微花一點時間去 tune 過，有沒有 SSR 差異應該不會太大。（因為現在最肥的是字型檔XD）

如果在不改變伺服器架構的情況下：
- 我們可以把追蹤的單詞單獨抽出來成一個 json 檔案，這樣可能更好懂一點？seed.rb 就去讀取這個檔案就好。
- frontend 其實有做 proxy，開發可以用 `yarn dev:prod` 就可以改連 production API。我們可以加上 CORS header 讓 server 允許所有來源的連線，這樣也可以做 Netlify preview。不過我目前真的沒有接到什麼前端的 pull request，現在改進這個可能有點太早。

這樣的話你覺得如何呢？我沒有仔細研究 Svelte 有沒有什麼好的 pre-render 方案（像是 Next.js）之類的，不然 setup 也得花一點時間研究。如果你很有興趣幫忙改善架構，歡迎送 PR 給我。我可以協助 dump DB 出來 seed 初始的 json 資料檔案。

謝謝！

**Comment by kevin940726** [comment]
前天稍微研究了一下，結論是如果要改動的話覺得要動到太多東西了效益不怎麼高，如果目前維護上也沒什麼難度和需要花費任何錢的話好像的確不需要改，可能看看以後如果有其他的需求的話再說吧 😅。

拆出成 json 或 yaml 檔之類的我覺得都不錯，不過關鍵應該還是要加上 `CONTRIBUTING.md` 告訴大家如何增加新詞。用 json 檔的話可能會因為 trailing comma 的問題讓不同 PR 有衝突會比較麻煩一些就是了。

有稍微研究了一下 svelte 的 pre-rendering 方案，看起來並不會太複雜，可能就是多加一個 `build.js` 執行在 `snowpack build` 之後就好，但目前看起來能帶來的好處對 SEO 的優化比較多，如果你認為這是可以優化的目標的話我很樂意提個 draft PR :)。感謝！

**Comment by itszero** [comment]
`CONTRIBUTING.md` 剛剛補上了！ `seed.rb` 也加上了 trailing comma 所以以後也不會 PR 之間衝突了。

我覺得目前來說 SEO 對這個網站好像沒有太多幫助 XD Google 理論上有支援一些情況的 JS 執行，加上也有 description tag。（實際搜尋了一下好像還真的有跑 JS，因為有截到字詞數量，雖然有點舊XD）不然就先這樣吧！還是很感謝你的意見跟指教！ 👍
